### ISSUE TITLE
Understaing the types of Features

### ISSUE THREAD

**Issue by lukik** [ninjabit/django-flexible-plans#2]
* django-flexible-plans version: 0.1.0

Thanks for trying to create a more modern billing/subscription package for Django. 

Am new to billing/pricing so mine is more of a question to understand the various Features you have described. 

In the documentation you have:

1. BaseFeature  
2. Feature
3. _MeteredFeature_
4. _CumulativeFeature_
5. _PermissionFeature_

In what scenarios would one use Metered, Cumulative and Permission feature? Do you have links where I can read more about this?

To try and understand this features I looked at the code and saw under `MeteredFeature` you have `units` and `usage` and I don't quite understand. I would have thought `units` would mean unit of measure but then I see its an integer value so it can't be a unit of measure because you would then have a reference table for it. The same confusion applies to `CumulativeFeature` as you only have `usage`. 

Thanks.

**Comment by tobiaghiraldini** [comment]
Hi lulik
This package is under heavy development and still it’s not ready to use. Therefore I’m looking for contributors to help me craft this package - or better - this set of packages (they are gonna be 3: plans, payments and billing), as I see they’re needed all over the places with different configurations, features, options.
To answer you question though, the Feature functionality is only raw code from which I need to start working and write the parts that define the different features types as follows:
Feature: is about a named feature. In a project you might have a specific feature, “register” for example, and you can define this type of feature by name or by choice.
MeteredFeature: is about a feature that you can use until a limit that’s set ( by the plan for example).
CumulativeFeature: is about a feature you can use within the limit, and my idea is to let the unused amount to be prorated and used in the next billing cycle.
PermissionFeature: is just a feature that’s connected with the permission system, so once the user subscribe to a Plan which is connected with a Group, all the features that require that specific Group/Permissions are enabled.

I hope I answered you questions. Ask if I overlooked something.
Also, feel free to comment or suggest a better approach if you have something in mind that’s not included here.

Up until now I am the only one who’s writing these packages, so any help would be greatly appreciated.
The road map of the 3 packages I mentioned before, is:
Django-flexible-plans: the package handling all the plans and subscriptions details, with plans’ features and mechanisms to handle the users subscriptions flow.
Django-flexible-payments: the package handling the payments. It’s intended to leverage the concept of a purchase order, and checkout, and connect with different providers. It can use the plan from the previous package as the order content and proceed with the payment flow (of course flexible-plans can be connected with plans provider, in which case the payment provider will be selected accordingly).
Django-flexible-billing: the package handling the billing/invoicing. It can leverage the countries’ different flows for billing and invoicing, connecting to vies to check the correct VAT number and implement the digital invoicing flow, now active in some Europe’s countries.
